[mypy]
python_version = 3.10
explicit_package_bases = True
namespace_packages = True
ignore_missing_imports = True
warn_unused_ignores = False
pretty = True
show_error_codes = True
no_implicit_optional = True
cache_dir = /tmp/iow/mypy_cache

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-docker.*]
ignore_missing_imports = True

[mypy-git.*]
ignore_missing_imports = True

[mypy-ollama.*]
ignore_missing_imports = True

[mypy-sse_starlette.*]
ignore_missing_imports = True
