"""
Inception-of-Wisdom (IoW) — Chapter VI: Bonus Part
Pull Request & Human-in-the-Loop Review Manager
Subject requirement: 'Open a Pull Request on a real remote (Gitea or local mirror)
so a human can review the auto-heal before it lands.'
"""

from __future__ import annotations

import os
import time
import json
import difflib
import logging
import subprocess
from typing import Optional, List, Dict, Any, Tuple
from dataclasses import dataclass, asdict, field

from p3.git_manager import GitManager

logger = logging.getLogger("bonus.pr_manager")

DEFAULT_PR_STORE = os.environ.get("IOW_PR_STORE", "/tmp/iow_cache/pull_requests.json")


@dataclass
class PullRequestRecord:
    """Represents a human-reviewable Pull Request generated by the self-healing agent."""
    pr_id: str
    title: str
    branch_name: str
    base_revision: str
    status: str                         # 'pending_review', 'merged', 'rejected'
    diagnosis_summary: str
    files_changed: List[str]
    unified_diff: str
    markdown_body: str
    created_at: float = field(default_factory=time.time)
    resolved_at: Optional[float] = None
    reviewer_comment: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class PullRequestManager:
    """Manages creation, diff generation, and human review/merging of self-healing Pull Requests."""

    def __init__(
        self,
        git_manager: GitManager,
        store_path: Optional[str] = None
    ):
        self.git_manager = git_manager
        self.store_path = os.path.abspath(store_path or DEFAULT_PR_STORE)
        self.prs: Dict[str, PullRequestRecord] = {}

        self._load_store()

    def _load_store(self) -> None:
        """Loads PR records from disk."""
        if not os.path.isfile(self.store_path):
            self.prs = {}
            return

        try:
            with open(self.store_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                for pr_dict in data.get("prs", []):
                    rec = PullRequestRecord(**pr_dict)
                    self.prs[rec.pr_id] = rec
                logger.info(f"Loaded {len(self.prs)} pull requests from {self.store_path}")
        except Exception as e:
            logger.error(f"Failed to load PR store from {self.store_path}: {e}")
            self.prs = {}

    def _save_store(self) -> None:
        """Saves PR records atomically to disk."""
        try:
            os.makedirs(os.path.dirname(self.store_path), exist_ok=True)
            tmp_file = f"{self.store_path}.tmp.{os.getpid()}"
            payload = {
                "updated_at": time.time(),
                "prs": [pr.to_dict() for pr in self.prs.values()]
            }
            with open(tmp_file, "w", encoding="utf-8") as f:
                json.dump(payload, f, indent=2)
            os.replace(tmp_file, self.store_path)
        except Exception as e:
            logger.error(f"Failed to save PR store to {self.store_path}: {e}")

    def generate_diff(self, file_path: str, new_content: str) -> str:
        """Generates unified diff between original on-disk file and proposed new content."""
        full_path = os.path.join(self.git_manager.repo_dir, file_path)
        old_lines = []
        if os.path.isfile(full_path):
            try:
                with open(full_path, "r", encoding="utf-8", errors="replace") as f:
                    old_lines = f.readlines()
            except Exception as e:
                logger.warning(f"Could not read old file {full_path} for diff: {e}")

        new_lines = [line if line.endswith("\n") else line + "\n" for line in new_content.splitlines(keepends=True)]

        diff = difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=f"a/{file_path}",
            tofile=f"b/{file_path}",
            lineterm=""
        )
        return "\n".join(diff)

    def create_pull_request(
        self,
        cycle_id: str,
        diagnosis_summary: str,
        patch_files: List[Dict[str, Any]],
        base_revision: Optional[str] = None
    ) -> PullRequestRecord:
        """Creates a review branch and generates a formatted Pull Request."""
        pr_id = f"pr-{cycle_id}"
        branch_name = f"iow/review/{cycle_id}"
        base_rev = base_revision or self.git_manager.get_current_head() or "HEAD"

        # Generate combined unified diff
        diff_chunks: List[str] = []
        files_changed: List[str] = []

        for pf in patch_files:
            rel_path = pf.get("path", "unknown")
            content = pf.get("content", "")
            files_changed.append(rel_path)
            f_diff = self.generate_diff(rel_path, content)
            if f_diff:
                diff_chunks.append(f_diff)

        full_diff = "\n\n".join(diff_chunks) if diff_chunks else "No textual diff generated."

        # Build Markdown PR description
        title = f"[IoW Auto-Heal] Fix: {diagnosis_summary[:60]}..."
        markdown_body = f"""# {title}

### 📋 Incident Diagnosis
{diagnosis_summary}

### 🛠️ Modified Files ({len(files_changed)})
{chr(10).join([f"- `{f}`" for f in files_changed])}

### 🔍 Unified Diff Preview
```diff
{full_diff}
```

---
*Created autonomously by Inception of Wisdom (IoW) Human-in-the-Loop Review Agent.*
"""

        # Create isolated git review branch
        try:
            self.git_manager._run_git(["checkout", "-B", branch_name], check=False)
            # Apply files to review branch
            for pf in patch_files:
                self.git_manager._write_file_atomically(pf.get("path"), pf.get("content", ""))
            self.git_manager._run_git(["add", "-A"], check=False)
            self.git_manager._run_git(["commit", "-m", f"review: {title}"], check=False)
            # Switch back to base
            self.git_manager._run_git(["checkout", self.git_manager.heal_branch], check=False)
            logger.info(f"Created review branch '{branch_name}' for PR [{pr_id}]")
        except Exception as e:
            logger.error(f"Error creating git branch for PR: {e}")

        pr_record = PullRequestRecord(
            pr_id=pr_id,
            title=title,
            branch_name=branch_name,
            base_revision=base_rev,
            status="pending_review",
            diagnosis_summary=diagnosis_summary,
            files_changed=files_changed,
            unified_diff=full_diff,
            markdown_body=markdown_body,
            created_at=time.time()
        )

        self.prs[pr_id] = pr_record
        self._save_store()
        logger.info(f"📬 Pull Request [{pr_id}] registered and waiting for human review.")
        return pr_record

    def list_prs(self, status_filter: Optional[str] = None) -> List[Dict[str, Any]]:
        """Returns list of PRs, newest first."""
        results = list(self.prs.values())
        if status_filter:
            results = [pr for pr in results if pr.status == status_filter]
        results.sort(key=lambda r: r.created_at, reverse=True)
        return [r.to_dict() for r in results]

    def get_pr(self, pr_id: str) -> Optional[PullRequestRecord]:
        return self.prs.get(pr_id)

    def merge_pr(self, pr_id: str, comment: Optional[str] = None) -> Tuple[bool, str]:
        """Human approval: merges review branch into active heal branch."""
        pr = self.prs.get(pr_id)
        if not pr:
            return False, f"PR '{pr_id}' not found."

        if pr.status != "pending_review":
            return False, f"PR '{pr_id}' is already {pr.status}."

        try:
            # Checkout heal branch and merge review branch
            self.git_manager._run_git(["checkout", self.git_manager.heal_branch])
            self.git_manager._run_git(["merge", "--no-ff", pr.branch_name, "-m", f"Merge PR #{pr_id}: {pr.title}"])

            pr.status = "merged"
            pr.resolved_at = time.time()
            pr.reviewer_comment = comment or "Approved and merged by human operator."
            self._save_store()

            logger.info(f"🎉 Pull Request [{pr_id}] successfully MERGED into {self.git_manager.heal_branch}")
            return True, f"PR [{pr_id}] merged successfully."
        except Exception as e:
            logger.error(f"Failed to merge PR [{pr_id}]: {e}")
            return False, f"Git merge error: {str(e)}"

    def reject_pr(self, pr_id: str, reason: Optional[str] = None) -> Tuple[bool, str]:
        """Human rejection: discards the review branch."""
        pr = self.prs.get(pr_id)
        if not pr:
            return False, f"PR '{pr_id}' not found."

        try:
            # Delete review branch
            self.git_manager._run_git(["branch", "-D", pr.branch_name], check=False)
            pr.status = "rejected"
            pr.resolved_at = time.time()
            pr.reviewer_comment = reason or "Rejected by human reviewer."
            self._save_store()

            logger.info(f"🚫 Pull Request [{pr_id}] REJECTED.")
            return True, f"PR [{pr_id}] rejected."
        except Exception as e:
            logger.error(f"Failed to reject PR [{pr_id}]: {e}")
            return False, f"Error rejecting PR: {str(e)}"

